### ISSUE TITLE
Remove ads from excel viewer extension

### ISSUE THREAD

**Issue by samt-aq** [wijmo/gc-excelviewer#1]
I just opened an excel file today using your extension, and was greeted by a bright, large ad banner. Please provide a way to remove this. It doesn't make it more acceptable because it's an ad for one of your own products. 

<img width="952" alt="image" src="https://github.com/user-attachments/assets/6e52232d-a067-47e7-bbbb-5c87909a130c">

**Comment by yakamoz423** [comment]
There is a setting item introduced in v4.2.61. Disable it and the world is clean now.

```json
"excel-viewer.showInfo": false
```

![image](https://github.com/user-attachments/assets/91ac8876-b841-44db-9a7e-51eb05644651)
